import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitInfraestructura1758545008735 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
CREATE SCHEMA IF NOT EXISTS infraestructura;

CREATE  TABLE infraestructura.campus ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	codigo							 varchar(16) NOT NULL UNIQUE,
	nombre               varchar(128)  NOT NULL  ,
	direccion            varchar(256)  NOT NULL  ,
	coordenadas          point  NOT NULL  ,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	CONSTRAINT pk_campus PRIMARY KEY ( id )
 );

CREATE  TABLE infraestructura.facultades ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	codigo							 varchar(16) NOT NULL UNIQUE,
	nombre               varchar(128)  NOT NULL  ,
	nombre_corto         varchar(16)    ,
	coordenadas          point  NOT NULL  ,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	campus_id            integer  NOT NULL  ,
	CONSTRAINT pk_facultades PRIMARY KEY ( id ),
	CONSTRAINT fk_facultades_campus FOREIGN KEY ( campus_id ) REFERENCES infraestructura.campus( id )   
 );

CREATE INDEX idx_facultades_campus_id ON infraestructura.facultades  ( campus_id );

CREATE  TABLE infraestructura.tipo_ambientes ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	nombre               varchar(64)  NOT NULL  ,
	descripcion          varchar(256)  NOT NULL  ,
	descripcion_corta    varchar(32)    ,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	CONSTRAINT pk_tipo_ambientes PRIMARY KEY ( id )
 );

CREATE  TABLE infraestructura.tipo_bloques ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	nombre               varchar(64)  NOT NULL  ,
	descripcion          varchar(256)  NOT NULL  ,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	CONSTRAINT pk_tipo_bloque PRIMARY KEY ( id )
 );

CREATE  TABLE infraestructura.bloques ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	nombre               varchar(128)  NOT NULL  ,
	nombre_corto         varchar(32)    ,
	codigo							 varchar(16) NOT NULL UNIQUE,
	pisos                smallint NOT NULL,
	coordenadas          point  NOT NULL,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	facultad_id          integer  NOT NULL  ,
	tipo_bloque_id       integer  NOT NULL  ,
	CONSTRAINT pk_bloques PRIMARY KEY ( id ),
	CONSTRAINT fk_bloques_facultades FOREIGN KEY ( facultad_id ) REFERENCES infraestructura.facultades( id )   ,
	CONSTRAINT fk_bloques_tipo_bloque FOREIGN KEY ( tipo_bloque_id ) REFERENCES infraestructura.tipo_bloques( id )   
 );

CREATE INDEX idx_bloques_facultad_id ON infraestructura.bloques  ( facultad_id );

CREATE INDEX idx_bloques_tipo_bloque_id ON infraestructura.bloques  ( tipo_bloque_id );

CREATE  TABLE infraestructura.ambientes ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	nombre               varchar(64)  NOT NULL  ,
	nombre_corto         varchar(16)    ,
	codigo							 varchar(16) NOT NULL UNIQUE,
	piso                 smallint NOT NULL,
	capacidad            jsonb DEFAULT '{"total":0,"examen":0}'::jsonb   ,
	dimension            jsonb DEFAULT '{"largo":0,"ancho":0,"alto":0,"unid_med":"metros"}'::jsonb   ,
	clases               boolean  NOT NULL  ,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	tipo_ambiente_id     integer  NOT NULL  ,
	bloque_id            integer  NOT NULL  ,
	CONSTRAINT pk_ambientes PRIMARY KEY ( id ),
	CONSTRAINT fk_ambientes_tipo_ambientes FOREIGN KEY ( tipo_ambiente_id ) REFERENCES infraestructura.tipo_ambientes( id )   ,
	CONSTRAINT fk_ambientes_bloques FOREIGN KEY ( bloque_id ) REFERENCES infraestructura.bloques( id )   
 );

CREATE INDEX idx_ambientes_tipo_ambiente_id ON infraestructura.ambientes  ( tipo_ambiente_id );

CREATE INDEX idx_ambientes_bloque_id ON infraestructura.ambientes  ( bloque_id );

CREATE INDEX idx_ambientes_capacidad_gin ON infraestructura.ambientes USING GIN ( capacidad );

CREATE  TABLE infraestructura.activos ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	NIA                  varchar(32)  NOT NULL  ,
	nombre               varchar(32)  NOT NULL  ,
	descripcion          varchar(128)    ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	ambiente_id          integer    ,
	CONSTRAINT pk_activos PRIMARY KEY ( id ),
	CONSTRAINT fk_activos_ambientes FOREIGN KEY ( ambiente_id ) REFERENCES infraestructura.ambientes( id )   
 );

CREATE INDEX idx_activos_ambiente_id ON infraestructura.activos  ( ambiente_id );

-- infraestructura
CREATE OR REPLACE FUNCTION infraestructura.tg_touch_actualizado_en()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- Si es INSERT, fija el timestamp de ahora si vino nulo
  IF TG_OP = 'INSERT' THEN
    NEW.actualizado_en := COALESCE(NEW.actualizado_en, CURRENT_TIMESTAMP);
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF (to_jsonb(NEW) - 'actualizado_en') IS DISTINCT FROM (to_jsonb(OLD) - 'actualizado_en') THEN
      NEW.actualizado_en := CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION infraestructura.tg_validar_capacidad_ambiente()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_total_text  text;
  v_examen_text text;
BEGIN
  IF NEW.capacidad IS NULL THEN
    RAISE EXCEPTION 'capacidad no puede ser NULL y debe incluir total y examen';
  END IF;

  IF NOT (NEW.capacidad ? 'total' AND NEW.capacidad ? 'examen') THEN
    RAISE EXCEPTION 'El campo capacidad debe contener las claves: total y examen';
  END IF;

  v_total_text  := NEW.capacidad->>'total';
  v_examen_text := NEW.capacidad->>'examen';

  IF jsonb_typeof(NEW.capacidad->'total') <> 'number'
     OR jsonb_typeof(NEW.capacidad->'examen') <> 'number' THEN
     RAISE EXCEPTION 'total y examen deben ser números (JSON number)';
  END IF;

  -- Deben ser enteros >= 0  (regex: 1,2,3,... sin decimales ni signo)
  IF v_total_text  !~ '^(?:0|[1-9][[:digit:]]*)$'
     OR v_examen_text !~ '^(?:0|[1-9][[:digit:]]*)$' THEN
     RAISE EXCEPTION 'total y examen deben ser enteros >= 0';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION infraestructura.tg_validar_dimension_ambiente()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_largo numeric;
  v_ancho numeric;
  v_alto  numeric;
  v_unid  text;
BEGIN
  IF NEW.dimension IS NULL THEN
    RAISE EXCEPTION 'dimension no puede ser NULL';
  END IF;

  IF NOT (NEW.dimension ? 'largo'
          AND NEW.dimension ? 'ancho'
          AND NEW.dimension ? 'alto'
          AND NEW.dimension ? 'unid_med') THEN
    RAISE EXCEPTION 'dimension debe contener las claves: largo, ancho, alto, unid_med';
  END IF;

  IF jsonb_typeof(NEW.dimension->'largo')    <> 'number'
     OR jsonb_typeof(NEW.dimension->'ancho') <> 'number'
     OR jsonb_typeof(NEW.dimension->'alto')  <> 'number'
     OR jsonb_typeof(NEW.dimension->'unid_med') <> 'string' THEN
    RAISE EXCEPTION 'largo/ancho/alto deben ser números y unid_med debe ser texto';
  END IF;

  v_largo := (NEW.dimension->>'largo')::numeric;
  v_ancho := (NEW.dimension->>'ancho')::numeric;
  v_alto  := (NEW.dimension->>'alto')::numeric;
  v_unid  := lower(NEW.dimension->>'unid_med');

  IF v_largo < 0 OR v_ancho < 0 OR v_alto < 0 THEN
    RAISE EXCEPTION 'largo, ancho y alto deben ser >= 0';
  END IF;

  -- Ajusta el listado según tu catálogo de unidades
  IF v_unid NOT IN ('metros','centimetros','milimetros') THEN
    RAISE EXCEPTION 'unid_med inválida. Use metros, centimetros o milimetros';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_activos_touch_actualizado_en ON infraestructura.activos;
CREATE TRIGGER tr_activos_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.activos
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_ambientes_biu_validar_capacidad ON infraestructura.ambientes;

CREATE TRIGGER tr_ambientes_biu_validar_capacidad
BEFORE INSERT OR UPDATE ON infraestructura.ambientes
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_validar_capacidad_ambiente();

DROP TRIGGER IF EXISTS tr_ambientes_biu_validar_dimension ON infraestructura.ambientes;

CREATE TRIGGER tr_ambientes_biu_validar_dimension
BEFORE INSERT OR UPDATE ON infraestructura.ambientes
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_validar_dimension_ambiente();

DROP TRIGGER IF EXISTS tr_ambientes_touch_actualizado_en ON infraestructura.ambientes;
CREATE TRIGGER tr_ambientes_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.ambientes
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_bloques_touch_actualizado_en ON infraestructura.bloques;
CREATE TRIGGER tr_bloques_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.bloques
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_campus_touch_actualizado_en ON infraestructura.campus;
CREATE TRIGGER tr_campus_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.campus
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_facultades_touch_actualizado_en ON infraestructura.facultades;
CREATE TRIGGER tr_facultades_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.facultades
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_tipo_ambientes_touch_actualizado_en ON infraestructura.tipo_ambientes;
CREATE TRIGGER tr_tipo_ambientes_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.tipo_ambientes
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_tipo_bloques_touch_actualizado_en ON infraestructura.tipo_bloques;
CREATE TRIGGER tr_tipo_bloques_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.tipo_bloques
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

COMMENT ON TABLE infraestructura.campus IS 'Tabla que almacena los campus de la universidad (Ej: central, medicina, etc)';

COMMENT ON COLUMN infraestructura.campus.id IS 'Clave unica de cada campus';

COMMENT ON COLUMN infraestructura.campus.nombre IS 'Nombre del campus';

COMMENT ON COLUMN infraestructura.campus.direccion IS 'Direccion del campus';

COMMENT ON COLUMN infraestructura.campus.coordenadas IS 'Coordenadas del campus';

COMMENT ON COLUMN infraestructura.campus.activo IS 'Indica si el campues esta activo';

COMMENT ON COLUMN infraestructura.campus.creado_en IS 'Fecha en la que se creo el registro';

COMMENT ON COLUMN infraestructura.campus.actualizado_en IS 'Fecha de la ultima vez en la que se actualizo el registro';

COMMENT ON TABLE infraestructura.facultades IS 'Tabla que almacena las facultades';

COMMENT ON COLUMN infraestructura.facultades.id IS 'Clave unica o codigo de la facultad';

COMMENT ON COLUMN infraestructura.facultades.nombre IS 'Nombre de la facultad';

COMMENT ON COLUMN infraestructura.facultades.nombre_corto IS 'Nombre corto de la facultad';

COMMENT ON COLUMN infraestructura.facultades.coordenadas IS 'coordenadas de la facultad';

COMMENT ON COLUMN infraestructura.facultades.activo IS 'Indica si la facultad esta activo';

COMMENT ON COLUMN infraestructura.facultades.creado_en IS 'Fecha en la que se creo el registro';

COMMENT ON COLUMN infraestructura.facultades.actualizado_en IS 'Ultima fecha en la que se actualizo el registro';

COMMENT ON COLUMN infraestructura.facultades.campus_id IS 'Referencia la llave de la tabla campus';

COMMENT ON COLUMN infraestructura.tipo_ambientes.id IS 'Clave unica del tipo de ambiente';

COMMENT ON COLUMN infraestructura.tipo_ambientes.nombre IS 'Nombre del tipo de ambiente (Ej: Laboratorio de quimica)';

COMMENT ON COLUMN infraestructura.tipo_ambientes.descripcion IS 'Alguna descripcion adicional sobre el tipo de ambiente';

COMMENT ON COLUMN infraestructura.tipo_ambientes.descripcion_corta IS 'Descripcion corta sobre le tipo de ambiente';

COMMENT ON COLUMN infraestructura.tipo_ambientes.activo IS 'Este tipo de ambiente esta activo?';

COMMENT ON COLUMN infraestructura.tipo_ambientes.creado_en IS 'Indica la fecha de creacion de este tipo de ambiente';

COMMENT ON COLUMN infraestructura.tipo_ambientes.actualizado_en IS 'Indica la fecha de la ultima actualizacion del registro';

COMMENT ON COLUMN infraestructura.tipo_bloques.id IS 'Clave unica para cada tipo de bloque';

COMMENT ON TABLE infraestructura.bloques IS 'Tabla que guarda los bloques (Edificios o conjunto de edificios que contienen ambientes)';

COMMENT ON COLUMN infraestructura.bloques.id IS 'Clave unica para cada bloque';

COMMENT ON COLUMN infraestructura.bloques.nombre IS 'Nombre del bloque';

COMMENT ON COLUMN infraestructura.bloques.nombre_corto IS 'Nombre corto del bloque';

COMMENT ON COLUMN infraestructura.bloques.codigo IS 'Codigo del bloque';

COMMENT ON COLUMN infraestructura.bloques.pisos IS 'Cantidad de pisos que se tiene en el bloque';

COMMENT ON COLUMN infraestructura.bloques.activo IS 'Indica si el bloque esta activo';

COMMENT ON COLUMN infraestructura.bloques.creado_en IS 'Fecha de creacion del registro';

COMMENT ON COLUMN infraestructura.bloques.actualizado_en IS 'Ultima fecha de actualizacion del registro';

COMMENT ON COLUMN infraestructura.bloques.facultad_id IS 'Llave foranea a la tabla facultades';

COMMENT ON TABLE infraestructura.ambientes IS 'Tabla encargada de guardar informacion relacionada a los ambientes';

COMMENT ON COLUMN infraestructura.ambientes.id IS 'Clave unica de cada ambiente';

COMMENT ON COLUMN infraestructura.ambientes.nombre IS 'Nombre del ambiente (691A, 691B, etc)';

COMMENT ON COLUMN infraestructura.ambientes.nombre_corto IS 'Nombre corto del ambiente';

COMMENT ON COLUMN infraestructura.ambientes.codigo IS 'codigo de cada ambiente manejado por la UMSS';

COMMENT ON COLUMN infraestructura.ambientes.piso IS 'Indica en que piso esta situado el ambiente';

COMMENT ON COLUMN infraestructura.ambientes.capacidad IS 'Capacidad total del ambiente para una clase';

COMMENT ON COLUMN infraestructura.ambientes.dimension IS 'Largo, Ancho y Alto del ambiente';

COMMENT ON COLUMN infraestructura.ambientes.clases IS 'Indica si este ambiente puede ser usado como aula de clases';

COMMENT ON COLUMN infraestructura.ambientes.activo IS 'Indica si el ambiente esta activo para su uso';

COMMENT ON COLUMN infraestructura.ambientes.creado_en IS 'Creado en';

COMMENT ON COLUMN infraestructura.ambientes.actualizado_en IS 'Actualizado en';

COMMENT ON COLUMN infraestructura.ambientes.tipo_ambiente_id IS 'Referencia la clave primaria de un tipo de ambiente';

COMMENT ON COLUMN infraestructura.ambientes.bloque_id IS 'Referencia la clave de un bloque';

COMMENT ON TABLE infraestructura.activos IS 'Tabla que almacena todos los activos existentes';

COMMENT ON COLUMN infraestructura.activos.id IS 'Codigo unico del activo (NIA)';

COMMENT ON COLUMN infraestructura.activos.nombre IS 'Nombre del activo';

COMMENT ON COLUMN infraestructura.activos.descripcion IS 'Descripcion sobre el activo';

COMMENT ON COLUMN infraestructura.activos.creado_en IS 'Fecha en la que se creo el registro';

COMMENT ON COLUMN infraestructura.activos.actualizado_en IS 'Fecha de la ultima actualizacion del registro';

COMMENT ON COLUMN infraestructura.activos.ambiente_id IS 'Llave foranea a ambientes';

INSERT INTO infraestructura.tipo_bloques (nombre, descripcion)
VALUES
  ('Administrativo', 'Edificio con oficinas y servicios administrativos'),
  ('Laboratorios', 'Bloque equipados para practicas cientificas y de computacion'),
  ('Aulas', 'Bloque con aulas para clases convencionales'),
  ('Investigacion', 'Bloque destinado a centros de investigacion y desarrollo tecnologico'),
  ('Servicios estudiantiles', 'Edificios que brindan servicios de bienestar y apoyo al estudiante');

INSERT INTO infraestructura.tipo_ambientes (nombre, descripcion, descripcion_corta)
VALUES
  ('Clases', 'Aula para clases de pizarra', 'Basica'),
  ('Laboratorio de computacion', 'Aula equipada con computadoras personales', 'Laboratorio de computadoras'),
  ('Laboratorio de redes', 'Aula equipada con routers', NULL),
  ('Auditorio', 'Espacio amplio para conferencias y eventos institucionales', 'Auditorio'),
  ('Sala de reuniones', 'Ambiente destinado a reuniones administrativas o academicas', 'Sala de reuniones');

INSERT INTO infraestructura.campus (codigo, nombre, direccion, coordenadas)
VALUES
  ('123456789', 'Campus central', 'Av Sucre entre Belzu y Oquendo', POINT(-66.5, -17.39)),
  ('987654321', 'Valle Sacta', 'Zona sacta', POINT(-63, -18)),
  ('555555555', 'Quillacollo', 'Blanco galindo', POINT(-70, -20)),
  ('222222222', 'Campus Sacaba', 'Av Villazon Km 12, Sacaba', POINT(-65.99, -17.41)),
  ('888888888', 'Campus Tiquipaya', 'Av Ecologica s/n, Tiquipaya', POINT(-65.73, -17.32)),
  ('444444444', 'Campus Cercado Norte', 'Calle Independencia esquina Aroma', POINT(-66.16, -17.37));

INSERT INTO infraestructura.facultades (codigo, nombre, nombre_corto, coordenadas, campus_id)
VALUES
  ('12345', 'Facultad de Ciencias y Tecnologia', 'FCyT', POINT(-66.5, -18), 1),
  ('54321', 'Facultad de Ciencias Economicas', 'FCE', POINT(-66, -18), 1),
  ('11225', 'Facultad Villa Sacta', NULL, POINT(-63, -18), 2),
  ('66789', 'Facultad de Arquitectura y Urbanismo', 'FAU', POINT(-66.52, -17.41), 3),
  ('77889', 'Facultad de Agronomia', 'FA', POINT(-65.98, -17.43), 4),
  ('88990', 'Facultad de Artes y Cultura', 'FAC', POINT(-65.73, -17.30), 5),
  ('99887', 'Facultad de Derecho y Ciencias Politicas', 'FDCP', POINT(-66.15, -17.36), 6);

INSERT INTO infraestructura.bloques (nombre, nombre_corto, codigo, pisos, coordenadas, facultad_id, tipo_bloque_id)
VALUES
  ('Edificio Nuevo de aulas', 'Edifico nuevo', '123456789', 3, POINT(-66,-18), 1, 3),
  ('Edifico de laboratorios', 'Edificio labos', '987654321', 4, POINT(-66,-19), 1, 2),
  ('Pasillo de gallineros', 'Edificio de aulas', '111112222', 1, POINT(-62,-18), 2, 3),
  ('Centro de Innovacion Tecnologica', 'Innovacion', 'INN-001', 5, POINT(-66.48, -17.40), 1, 4),
  ('Complejo Deportivo Universitario', 'Deportivo', 'DEP-002', 2, POINT(-66.47, -17.42), 2, 5),
  ('Bloque Agroindustrial', 'Agroindustrial', 'AGR-003', 3, POINT(-65.97, -17.44), 5, 2),
  ('Bloque Talleres Arquitectura', 'Talleres Arq', 'ARQ-004', 4, POINT(-66.53, -17.42), 4, 3);

INSERT INTO infraestructura.ambientes (nombre, nombre_corto, codigo, piso, capacidad, dimension, clases, tipo_ambiente_id, bloque_id)
VALUES
  ('691A', '691', '69111', 1, '{"total": 45, "examen":35}'::jsonb, '{"largo": 30, "ancho": 8, "alto": 3.4, "unid_med": "metros"}'::jsonb, TRUE, 1, 1),
  ('Laboratorio', 'LAbo', '77777', 0, '{"total": 30, "examen": 15}'::jsonb, '{"largo": 20, "ancho": 6, "alto": 3.4, "unid_med": "metros"}'::jsonb, TRUE, 1, 2),
  ('Laboratorio de redes 1', 'LabRed', '55555', 0, '{"total": 15, "examen": 1}'::jsonb, '{"largo": 15, "ancho": 8, "alto": 3.4, "unid_med": "metros"}'::jsonb, TRUE, 3, 2),
  ('Auditorio Central', 'AudCentral', 'AUD-001', 0, '{"total": 250, "examen": 200}'::jsonb, '{"largo": 40, "ancho": 20, "alto": 8, "unid_med": "metros"}'::jsonb, FALSE, 4, 4),
  ('Sala Consejo Academico', 'Consejo', 'CON-001', 1, '{"total": 40, "examen": 0}'::jsonb, '{"largo": 18, "ancho": 10, "alto": 4, "unid_med": "metros"}'::jsonb, FALSE, 5, 4),
  ('Laboratorio de Suelos', 'LabSuelos', 'LAB-AGR-01', 0, '{"total": 20, "examen": 10}'::jsonb, '{"largo": 18, "ancho": 9, "alto": 3.8, "unid_med": "metros"}'::jsonb, TRUE, 2, 6),
  ('Taller de Maquetas', 'Maquetas', 'TALL-ARQ-1', 1, '{"total": 35, "examen": 25}'::jsonb, '{"largo": 25, "ancho": 12, "alto": 4, "unid_med": "metros"}'::jsonb, TRUE, 1, 7);

INSERT INTO infraestructura.activos (nia, nombre, descripcion, ambiente_id)
VALUES
  (
    'NIA-0001',
    'Proyector Epson X12',
    'Proyector principal del auditorio central',
    (SELECT id FROM infraestructura.ambientes WHERE codigo = 'AUD-001')
  ),
  (
    'NIA-0002',
    'Router Cisco 2900',
    'Router principal del laboratorio de redes',
    (SELECT id FROM infraestructura.ambientes WHERE codigo = '55555')
  ),
  (
    'NIA-0003',
    'Computadora Lenovo AIO',
    'Equipo para practicas de software',
    (SELECT id FROM infraestructura.ambientes WHERE codigo = '77777')
  ),
  (
    'NIA-0004',
    'Aire acondicionado Samsung 36k',
    'Equipo de climatizacion del consejo academico',
    (SELECT id FROM infraestructura.ambientes WHERE codigo = 'CON-001')
  ),
  (
    'NIA-0005',
    'Juego de pupitres metalicos',
    'Lote de 30 pupitres para aulas',
    (SELECT id FROM infraestructura.ambientes WHERE codigo = '69111')
  );
            `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
			DROP SCHEMA IF EXISTS infraestructura CASCADE;
    `);
  }
}
