import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitInfraestructura1758545008735 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
CREATE SCHEMA IF NOT EXISTS infraestructura;

CREATE  TABLE infraestructura.campus ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	codigo							 varchar(16) NOT NULL UNIQUE,
	nombre               varchar(128)  NOT NULL  ,
	direccion            varchar(256)  NOT NULL  ,
	coordenadas          point  NOT NULL  ,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	CONSTRAINT pk_campus PRIMARY KEY ( id )
 );

CREATE  TABLE infraestructura.facultades ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	codigo							 varchar(16) NOT NULL UNIQUE,
	nombre               varchar(128)  NOT NULL  ,
	nombre_corto         varchar(16)    ,
	coordenadas          point  NOT NULL  ,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	campus_id            integer  NOT NULL  ,
	CONSTRAINT pk_facultades PRIMARY KEY ( id ),
	CONSTRAINT fk_facultades_campus FOREIGN KEY ( campus_id ) REFERENCES infraestructura.campus( id )   
 );

CREATE INDEX idx_facultades_campus_id ON infraestructura.facultades  ( campus_id );

CREATE  TABLE infraestructura.tipo_ambientes ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	nombre               varchar(64)  NOT NULL  ,
	descripcion          varchar(256)  NOT NULL  ,
	descripcion_corta    varchar(32)    ,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	CONSTRAINT pk_tipo_ambientes PRIMARY KEY ( id )
 );

CREATE  TABLE infraestructura.tipo_bloques ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	nombre               varchar(64)  NOT NULL  ,
	descripcion          varchar(256)  NOT NULL  ,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	CONSTRAINT pk_tipo_bloque PRIMARY KEY ( id )
 );

CREATE  TABLE infraestructura.bloques ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	nombre               varchar(128)  NOT NULL  ,
	nombre_corto         varchar(16)    ,
	codigo							 varchar(16) NOT NULL UNIQUE,
	pisos                smallint NOT NULL,
	coordenadas          point  NOT NULL,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	facultad_id          integer  NOT NULL  ,
	tipo_bloque_id       integer  NOT NULL  ,
	CONSTRAINT pk_bloques PRIMARY KEY ( id ),
	CONSTRAINT fk_bloques_facultades FOREIGN KEY ( facultad_id ) REFERENCES infraestructura.facultades( id )   ,
	CONSTRAINT fk_bloques_tipo_bloque FOREIGN KEY ( tipo_bloque_id ) REFERENCES infraestructura.tipo_bloques( id )   
 );

CREATE INDEX idx_bloques_facultad_id ON infraestructura.bloques  ( facultad_id );

CREATE INDEX idx_bloques_tipo_bloque_id ON infraestructura.bloques  ( tipo_bloque_id );

CREATE  TABLE infraestructura.ambientes ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	nombre               varchar(64)  NOT NULL  ,
	nombre_corto         varchar(16)    ,
	codigo							 varchar(16) NOT NULL UNIQUE,
	piso                 smallint NOT NULL,
	capacidad            jsonb DEFAULT '{"total":0,"examen":0}'::jsonb   ,
	dimension            jsonb DEFAULT '{"largo":0,"ancho":0,"alto":0,"unid_med":"metros"}'::jsonb   ,
	clases               boolean  NOT NULL  ,
	activo               boolean DEFAULT TRUE NOT NULL  ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	tipo_ambiente_id     integer  NOT NULL  ,
	bloque_id            integer  NOT NULL  ,
	CONSTRAINT pk_ambientes PRIMARY KEY ( id ),
	CONSTRAINT fk_ambientes_tipo_ambientes FOREIGN KEY ( tipo_ambiente_id ) REFERENCES infraestructura.tipo_ambientes( id )   ,
	CONSTRAINT fk_ambientes_bloques FOREIGN KEY ( bloque_id ) REFERENCES infraestructura.bloques( id )   
 );

CREATE INDEX idx_ambientes_tipo_ambiente_id ON infraestructura.ambientes  ( tipo_ambiente_id );

CREATE INDEX idx_ambientes_bloque_id ON infraestructura.ambientes  ( bloque_id );

CREATE INDEX idx_ambientes_capacidad_gin ON infraestructura.ambientes USING GIN ( capacidad );

CREATE  TABLE infraestructura.activos ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1  START WITH 1  ) ,
	NIA                  varchar(32)  NOT NULL  ,
	nombre               varchar(32)  NOT NULL  ,
	descripcion          varchar(128)    ,
	creado_en            timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	actualizado_en       timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	ambiente_id          integer    ,
	CONSTRAINT pk_activos PRIMARY KEY ( id ),
	CONSTRAINT fk_activos_ambientes FOREIGN KEY ( ambiente_id ) REFERENCES infraestructura.ambientes( id )   
 );

CREATE INDEX idx_activos_ambiente_id ON infraestructura.activos  ( ambiente_id );

-- infraestructura
CREATE OR REPLACE FUNCTION infraestructura.tg_touch_actualizado_en()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- Si es INSERT, fija el timestamp de ahora si vino nulo
  IF TG_OP = 'INSERT' THEN
    NEW.actualizado_en := COALESCE(NEW.actualizado_en, CURRENT_TIMESTAMP);
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF (to_jsonb(NEW) - 'actualizado_en') IS DISTINCT FROM (to_jsonb(OLD) - 'actualizado_en') THEN
      NEW.actualizado_en := CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION infraestructura.tg_validar_capacidad_ambiente()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_total_text  text;
  v_examen_text text;
BEGIN
  IF NEW.capacidad IS NULL THEN
    RAISE EXCEPTION 'capacidad no puede ser NULL y debe incluir total y examen';
  END IF;

  IF NOT (NEW.capacidad ? 'total' AND NEW.capacidad ? 'examen') THEN
    RAISE EXCEPTION 'El campo capacidad debe contener las claves: total y examen';
  END IF;

  v_total_text  := NEW.capacidad->>'total';
  v_examen_text := NEW.capacidad->>'examen';

  IF jsonb_typeof(NEW.capacidad->'total') <> 'number'
     OR jsonb_typeof(NEW.capacidad->'examen') <> 'number' THEN
     RAISE EXCEPTION 'total y examen deben ser números (JSON number)';
  END IF;

  -- Deben ser enteros >= 0  (regex: 1,2,3,... sin decimales ni signo)
  IF v_total_text  !~ '^(?:0|[1-9][[:digit:]]*)$'
     OR v_examen_text !~ '^(?:0|[1-9][[:digit:]]*)$' THEN
     RAISE EXCEPTION 'total y examen deben ser enteros >= 0';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION infraestructura.tg_validar_dimension_ambiente()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_largo numeric;
  v_ancho numeric;
  v_alto  numeric;
  v_unid  text;
BEGIN
  IF NEW.dimension IS NULL THEN
    RAISE EXCEPTION 'dimension no puede ser NULL';
  END IF;

  IF NOT (NEW.dimension ? 'largo'
          AND NEW.dimension ? 'ancho'
          AND NEW.dimension ? 'alto'
          AND NEW.dimension ? 'unid_med') THEN
    RAISE EXCEPTION 'dimension debe contener las claves: largo, ancho, alto, unid_med';
  END IF;

  IF jsonb_typeof(NEW.dimension->'largo')    <> 'number'
     OR jsonb_typeof(NEW.dimension->'ancho') <> 'number'
     OR jsonb_typeof(NEW.dimension->'alto')  <> 'number'
     OR jsonb_typeof(NEW.dimension->'unid_med') <> 'string' THEN
    RAISE EXCEPTION 'largo/ancho/alto deben ser números y unid_med debe ser texto';
  END IF;

  v_largo := (NEW.dimension->>'largo')::numeric;
  v_ancho := (NEW.dimension->>'ancho')::numeric;
  v_alto  := (NEW.dimension->>'alto')::numeric;
  v_unid  := lower(NEW.dimension->>'unid_med');

  IF v_largo < 0 OR v_ancho < 0 OR v_alto < 0 THEN
    RAISE EXCEPTION 'largo, ancho y alto deben ser >= 0';
  END IF;

  -- Ajusta el listado según tu catálogo de unidades
  IF v_unid NOT IN ('metros','centimetros','milimetros') THEN
    RAISE EXCEPTION 'unid_med inválida. Use metros, centimetros o milimetros';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_activos_touch_actualizado_en ON infraestructura.activos;
CREATE TRIGGER tr_activos_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.activos
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_ambientes_biu_validar_capacidad ON infraestructura.ambientes;

CREATE TRIGGER tr_ambientes_biu_validar_capacidad
BEFORE INSERT OR UPDATE ON infraestructura.ambientes
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_validar_capacidad_ambiente();

DROP TRIGGER IF EXISTS tr_ambientes_biu_validar_dimension ON infraestructura.ambientes;

CREATE TRIGGER tr_ambientes_biu_validar_dimension
BEFORE INSERT OR UPDATE ON infraestructura.ambientes
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_validar_dimension_ambiente();

DROP TRIGGER IF EXISTS tr_ambientes_touch_actualizado_en ON infraestructura.ambientes;
CREATE TRIGGER tr_ambientes_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.ambientes
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_bloques_touch_actualizado_en ON infraestructura.bloques;
CREATE TRIGGER tr_bloques_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.bloques
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_campus_touch_actualizado_en ON infraestructura.campus;
CREATE TRIGGER tr_campus_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.campus
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_facultades_touch_actualizado_en ON infraestructura.facultades;
CREATE TRIGGER tr_facultades_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.facultades
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_tipo_ambientes_touch_actualizado_en ON infraestructura.tipo_ambientes;
CREATE TRIGGER tr_tipo_ambientes_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.tipo_ambientes
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

DROP TRIGGER IF EXISTS tr_tipo_bloques_touch_actualizado_en ON infraestructura.tipo_bloques;
CREATE TRIGGER tr_tipo_bloques_touch_actualizado_en
BEFORE INSERT OR UPDATE ON infraestructura.tipo_bloques
FOR EACH ROW
EXECUTE FUNCTION infraestructura.tg_touch_actualizado_en();

COMMENT ON TABLE infraestructura.campus IS 'Tabla que almacena los campus de la universidad (Ej: central, medicina, etc)';

COMMENT ON COLUMN infraestructura.campus.id IS 'Clave unica de cada campus';

COMMENT ON COLUMN infraestructura.campus.nombre IS 'Nombre del campus';

COMMENT ON COLUMN infraestructura.campus.direccion IS 'Direccion del campus';

COMMENT ON COLUMN infraestructura.campus.coordenadas IS 'Coordenadas del campus';

COMMENT ON COLUMN infraestructura.campus.activo IS 'Indica si el campues esta activo';

COMMENT ON COLUMN infraestructura.campus.creado_en IS 'Fecha en la que se creo el registro';

COMMENT ON COLUMN infraestructura.campus.actualizado_en IS 'Fecha de la ultima vez en la que se actualizo el registro';

COMMENT ON TABLE infraestructura.facultades IS 'Tabla que almacena las facultades';

COMMENT ON COLUMN infraestructura.facultades.id IS 'Clave unica o codigo de la facultad';

COMMENT ON COLUMN infraestructura.facultades.nombre IS 'Nombre de la facultad';

COMMENT ON COLUMN infraestructura.facultades.nombre_corto IS 'Nombre corto de la facultad';

COMMENT ON COLUMN infraestructura.facultades.coordenadas IS 'coordenadas de la facultad';

COMMENT ON COLUMN infraestructura.facultades.activo IS 'Indica si la facultad esta activo';

COMMENT ON COLUMN infraestructura.facultades.creado_en IS 'Fecha en la que se creo el registro';

COMMENT ON COLUMN infraestructura.facultades.actualizado_en IS 'Ultima fecha en la que se actualizo el registro';

COMMENT ON COLUMN infraestructura.facultades.campus_id IS 'Referencia la llave de la tabla campus';

COMMENT ON COLUMN infraestructura.tipo_ambientes.id IS 'Clave unica del tipo de ambiente';

COMMENT ON COLUMN infraestructura.tipo_ambientes.nombre IS 'Nombre del tipo de ambiente (Ej: Laboratorio de quimica)';

COMMENT ON COLUMN infraestructura.tipo_ambientes.descripcion IS 'Alguna descripcion adicional sobre el tipo de ambiente';

COMMENT ON COLUMN infraestructura.tipo_ambientes.descripcion_corta IS 'Descripcion corta sobre le tipo de ambiente';

COMMENT ON COLUMN infraestructura.tipo_ambientes.activo IS 'Este tipo de ambiente esta activo?';

COMMENT ON COLUMN infraestructura.tipo_ambientes.creado_en IS 'Indica la fecha de creacion de este tipo de ambiente';

COMMENT ON COLUMN infraestructura.tipo_ambientes.actualizado_en IS 'Indica la fecha de la ultima actualizacion del registro';

COMMENT ON COLUMN infraestructura.tipo_bloques.id IS 'Clave unica para cada tipo de bloque';

COMMENT ON TABLE infraestructura.bloques IS 'Tabla que guarda los bloques (Edificios o conjunto de edificios que contienen ambientes)';

COMMENT ON COLUMN infraestructura.bloques.id IS 'Clave unica para cada bloque';

COMMENT ON COLUMN infraestructura.bloques.nombre IS 'Nombre del bloque';

COMMENT ON COLUMN infraestructura.bloques.nombre_corto IS 'Nombre corto del bloque';

COMMENT ON COLUMN infraestructura.bloques.codigo IS 'Codigo del bloque';

COMMENT ON COLUMN infraestructura.bloques.pisos IS 'Cantidad de pisos que se tiene en el bloque';

COMMENT ON COLUMN infraestructura.bloques.activo IS 'Indica si el bloque esta activo';

COMMENT ON COLUMN infraestructura.bloques.creado_en IS 'Fecha de creacion del registro';

COMMENT ON COLUMN infraestructura.bloques.actualizado_en IS 'Ultima fecha de actualizacion del registro';

COMMENT ON COLUMN infraestructura.bloques.facultad_id IS 'Llave foranea a la tabla facultades';

COMMENT ON TABLE infraestructura.ambientes IS 'Tabla encargada de guardar informacion relacionada a los ambientes';

COMMENT ON COLUMN infraestructura.ambientes.id IS 'Clave unica de cada ambiente';

COMMENT ON COLUMN infraestructura.ambientes.nombre IS 'Nombre del ambiente (691A, 691B, etc)';

COMMENT ON COLUMN infraestructura.ambientes.nombre_corto IS 'Nombre corto del ambiente';

COMMENT ON COLUMN infraestructura.ambientes.codigo IS 'codigo de cada ambiente manejado por la UMSS';

COMMENT ON COLUMN infraestructura.ambientes.piso IS 'Indica en que piso esta situado el ambiente';

COMMENT ON COLUMN infraestructura.ambientes.capacidad IS 'Capacidad total del ambiente para una clase';

COMMENT ON COLUMN infraestructura.ambientes.dimension IS 'Largo, Ancho y Alto del ambiente';

COMMENT ON COLUMN infraestructura.ambientes.clases IS 'Indica si este ambiente puede ser usado como aula de clases';

COMMENT ON COLUMN infraestructura.ambientes.activo IS 'Indica si el ambiente esta activo para su uso';

COMMENT ON COLUMN infraestructura.ambientes.creado_en IS 'Creado en';

COMMENT ON COLUMN infraestructura.ambientes.actualizado_en IS 'Actualizado en';

COMMENT ON COLUMN infraestructura.ambientes.tipo_ambiente_id IS 'Referencia la clave primaria de un tipo de ambiente';

COMMENT ON COLUMN infraestructura.ambientes.bloque_id IS 'Referencia la clave de un bloque';

COMMENT ON TABLE infraestructura.activos IS 'Tabla que almacena todos los activos existentes';

COMMENT ON COLUMN infraestructura.activos.id IS 'Codigo unico del activo (NIA)';

COMMENT ON COLUMN infraestructura.activos.nombre IS 'Nombre del activo';

COMMENT ON COLUMN infraestructura.activos.descripcion IS 'Descripcion sobre el activo';

COMMENT ON COLUMN infraestructura.activos.creado_en IS 'Fecha en la que se creo el registro';

COMMENT ON COLUMN infraestructura.activos.actualizado_en IS 'Fecha de la ultima actualizacion del registro';

COMMENT ON COLUMN infraestructura.activos.ambiente_id IS 'Llave foranea a ambientes';

INSERT INTO infraestructura.tipo_bloques (nombre, descripcion)
VALUES
	('Aulas', 'Bloque con aulas para clases convencionales'),
	('Laboratorios de computacion', 'Bloque equipados para practicas de computacion'),
  ('Servicios estudiantiles', 'Edificios que brindan servicios de bienestar y apoyo al estudiante'),
	('Canchas de Futbol 5', 'Canchas de cemento'),
	('Laboratorios basicos', 'Ambiente que tiene laboratorios basicos de FCyT');

INSERT INTO infraestructura.tipo_ambientes (nombre, descripcion, descripcion_corta)
VALUES
  ('Aula', 'Aula para clases de pizarra', 'Aula Basica'),
  ('Biblioteca', 'Ambiente con recursos bibliograficos', 'Biblio'),
  ('Laboratorio', 'Laboratorio', NULL),
  ('Oficina', 'Ambiente dedicado a administracion', 'Administracion'),
  ('Sala de Auditorio', 'Auditorio', NULL),
	('Taller', 'Ambiente de talleres', NULL),
	('Establo', 'Ambiente de tipo establo', NULL);

INSERT INTO infraestructura.campus (codigo, nombre, direccion, coordenadas)
VALUES
  ('CENTRAL-001', 'Las cuadras', 'Avenida Sucre entre Belzu y Oquendo', POINT(-66.15, -17.40));

INSERT INTO infraestructura.facultades (codigo, nombre, nombre_corto, coordenadas, campus_id)
VALUES
  ('FCyT-001', 'Facultad de Ciencias y Tecnologia', 'FCyT', POINT(-66.14486487964972,-17.393397309615214), 1),
  ('FCE-001', 'Facultad de Ciencias Economicas', 'FCE', POINT(-66.14731531857925,-17.395347687308856), 1);

INSERT INTO infraestructura.bloques (nombre, nombre_corto, codigo, pisos, coordenadas, facultad_id, tipo_bloque_id)
VALUES
  ('Departamento de Sistemas e Informatica', 'Laboratorios SisInfo', '12', 0, POINT(-66.14698981637378,-17.39294682572144), 1, 2),
  ('Trencito', NULL, '15', 0, POINT(-66.1463724143366,-17.394032080491442), 1, 1),
  ('Administracion central FCyT', 'Central FCyT', '24', 4, POINT(-66.14490250841264,-17.39340754787264), 1, 3),
  ('Edificio ELEKTRO', 'ELEKTRO', '26', 2, POINT(-66.1453477700777,-17.393781243876205), 1, 1),
  ('Bloque Tinglados FCyT', 'Tinglados FCyT', '27', 0, POINT(-66.14400942711285,-17.393498668275925), 1, 4),
  ('Departamento de Biologia', 'Sector Biologia', '28', 0, POINT(-66.14494045450982,-17.393934817354953), 1, 1),
	('Departamento de Fisica', 'Sector Fisica', '30', 0, POINT(-66.14479526795155,-17.39290587258516), 1, 1),
	('Departamento de Quimica', 'Sector Quimica', '33', 0, POINT(-66.14431780630657,-17.39350481128954), 1, 1),
	('Bloque Antiguo AgroQuimica', 'Quimica Antiguo', '37', 0, POINT(-66.14421596169757,-17.393837554166712), 1, 1),
	('Bloque Nuevo AgroQuimica', 'Quimica Nuevo', '38', 0, POINT(-66.14421596169757,-17.393837554166712), 1, 1),
	('Edificio MEMI', 'MEMI', '45', 2, POINT(-66.14696796353066,-17.39325909308398), 1, 2),
	('Alimentos y Aguas FCyT', 'Alimentos y Agua', '46', 0, POINT(-66.14445707610554,-17.39275741738934), 1, 2),
	('Departamento Industrial', 'Industrial', '47', 0, POINT(-66.14584132347993,-17.393305165272665), 1, 1),
	('Edificio Nuevo FCyT', 'Aulas FCyT', '191', 3, POINT(-66.14475757931423,-17.39480506463203), 1, 1),
	('Edificio Laboratorios Basicso FCyT', 'Lab Basicos FCyT', '201', 3, POINT(-66.14435512971008,-17.39457982455748), 1, 5);


INSERT INTO infraestructura.ambientes (nombre, nombre_corto, codigo, piso, capacidad, dimension, clases, tipo_ambiente_id, bloque_id)
  VALUES
  ('AULA DE CONSULTA PARA TESISTAS', 'INFDEP', 'FCyT-001', 0, '{"total": 1, "examen": 1}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 1),
  ('LABORATORIO INFORMATICA', 'INFLAB', 'FCyT-002', 0, '{"total": 80, "examen": 40}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 1),
  ('AULA 660 (TRENCITO)', '660', 'FCyT-003', 0, '{"total": 90, "examen": 60}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 2),
  ('AULA 661 (TRENCITO)', '661', 'FCyT-004', 0, '{"total": 90, "examen": 60}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 2),
  ('AULA 651', '651', 'FCyT-005', 0, '{"total": 120, "examen": 100}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 3),
  ('AULA 652', '652', 'FCyT-006', 0, '{"total": 50, "examen": 40}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 3),
  ('AULA CEMARR', 'CEMAR', 'FCyT-007', 0, '{"total": 45, "examen": 23}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 3),
  ('AULA DE CIVIL', 'CIVDEP', 'FCyT-008', 2, '{"total": 7, "examen": 7}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 3),
  ('PROCESAMIENTO DE DATOS', 'CPD', 'FCyT-009', 0, '{"total": 4, "examen": 4}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 3),
  ('DECANATO', 'DECDEP', 'FCyT-010', 1, '{"total": 7, "examen": 7}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 3),
  ('AULA MATEMATICAS', 'MATDEP', 'FCyT-011', 1, '{"total": 7, "examen": 7}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 3),
  ('AULA MECANICA', 'MECDEP', 'FCyT-012', 2, '{"total": 7, "examen": 7}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 3),
  ('COMPUTO MECANICA', 'MECGAB', 'FCyT-013', 2, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 6, 3),
  ('LABORATORIO 668 (ELEKTRO)', '668', 'FCyT-014', 0, '{"total": 60, "examen": 50}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 4),
  ('LABORATORIO 670 (ELEKTRO)', '670', 'FCyT-015', 1, '{"total": 50, "examen": 40}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 4),
  ('LABORATORIO 671 (ELEKTRO)', '671', 'FCyT-016', 2, '{"total": 25, "examen": 20}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 4),
  ('LABORATORIO 672 (ELEKTRO)', '672', 'FCyT-017', 2, '{"total": 130, "examen": 100}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 4),
  ('LABORATORIO 667A (ELEKTRO)', '667A', 'FCyT-018', 0, '{"total": 155, "examen": 120}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 4),
  ('LABORATORIO 667B (ELEKTRO)', '667B', 'FCyT-019', 0, '{"total": 50, "examen": 40}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 4),
  ('LABORATORIO 671A (ELEKTRO)', '671A', 'FCyT-020', 2, '{"total": 95, "examen": 70}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 4),
  ('671B (GABINETE PROYECTOS)', '671B', 'FCyT-021', 2, '{"total": 30, "examen": 15}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 4),
  ('LABORATORIO 671C (ELEKTRO)', '671C', 'FCyT-022', 2, '{"total": 40, "examen": 20}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 4),
  ('674A (LAB. TELECOMUNICACIONES)', '674A', 'FCyT-023', 3, '{"total": 30, "examen": 20}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 4),
  ('674B (LABORATORIO CONTROL)', '674B', 'FCyT-024', 3, '{"total": 30, "examen": 20}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 4),
  ('AUDITORIO POSGRADO ELEKTRO', 'AuPosEl', 'FCyT-025', 3, '{"total": 40, "examen": 40}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 5, 4),
  ('AULA ELECTRICIDAD', 'ELCDEP', 'FCyT-026', 2, '{"total": 1, "examen": 1}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 4),
  ('AULA 640 (PROYECTOS MECANICA)', '640', 'FCyT-027', 0, '{"total": 50, "examen": 25}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 5),
  ('AULA 642', '642', 'FCyT-028', 0, '{"total": 120, "examen": 80}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 5),
  ('AULA 606 (AUDITORIO BIOLOGIA)', '606', 'FCyT-029', 1, '{"total": 55, "examen": 40}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 5, 6),
  ('AULA 607', '607', 'FCyT-030', 0, '{"total": 190, "examen": 140}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 6),
  ('AULA 608 (LABORATORIO)', '608', 'FCyT-031', 0, '{"total": 35, "examen": 25}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 6),
  ('AULA 609 (LABO BIOLOGIA)', '609', 'FCyT-032', 0, '{"total": 12, "examen": 6}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 6),
  ('AULA 608A (LABO BIOLOGIA)', '608A', 'FCyT-033', 0, '{"total": 40, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 6),
  ('AULA 608B (LABO BIOLOGIA)', '608B', 'FCyT-034', 0, '{"total": 20, "examen": 15}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 6),
  ('AULA 609A (LABO BIOLOGIA)', '609A', 'FCyT-035', 0, '{"total": 20, "examen": 15}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 6),
  ('BIBLIOTECA BIOLOGIA', 'BIBLIO', 'FCyT-036', 1, '{"total": 20, "examen": 10}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 2, 6),
  ('AULA BIOLOGIA', 'BIODEP', 'FCyT-037', 1, '{"total": 1, "examen": 1}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 6),
  ('AULA CONSULTA GABINETE TESIS', 'GABI', 'FCyT-038', 1, '{"total": 1, "examen": 1}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 6),
  ('OFICINAS LIMNOLOGIA', 'LIMNOL', 'FCyT-039', 1, '{"total": 10, "examen": 10}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 6),
  ('AULA 617', '617', 'FCyT-040', 1, '{"total": 185, "examen": 140}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 7),
  ('AULA 618 (LABO FISICA)', '618', 'FCyT-041', 0, '{"total": 90, "examen": 70}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 7),
  ('AULA 619 (LABO FISICA)', '619', 'FCyT-042', 0, '{"total": 25, "examen": 20}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 7),
  ('AULA 620 (LABO FISICA)', '620', 'FCyT-043', 0, '{"total": 60, "examen": 50}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 7),
  ('AULA 621 (LABO FISICA)', '621', 'FCyT-044', 0, '{"total": 20, "examen": 10}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 7),
  ('AULA 617B (IZQUIERDA)', '617B', 'FCyT-045', 0, '{"total": 90, "examen": 70}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 7),
  ('AULA 617C (DERECHA)', '617C', 'FCyT-046', 0, '{"total": 80, "examen": 60}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 7),
  ('AULA 620B (LABO FISICA)DEPSITO', '620B', 'FCyT-047', 0, '{"total": 15, "examen": 10}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 7),
  ('AULA 621A (LABO FISICA)', '621A', 'FCyT-048', 0, '{"total": 25, "examen": 20}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 7),
  ('GABINETE DE COMPUTACION', 'FISCOM', 'FCyT-049', 1, '{"total": 20, "examen": 20}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 7),
  ('AULA FISICA', 'FISDEP', 'FCyT-050', 1, '{"total": 7, "examen": 7}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 7),
  ('AULA 612', '612', 'FCyT-051', 0, '{"total": 210, "examen": 160}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 8),
  ('AULA 613 (LABO QUIMICA)', '613', 'FCyT-052', 0, '{"total": 75, "examen": 60}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 8),
  ('AULA 614 (LABO QUIMICA)', '614', 'FCyT-053', 0, '{"total": 75, "examen": 60}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 8),
  ('AULA 615 (LABO QUIMICA)', '615', 'FCyT-054', 0, '{"total": 65, "examen": 50}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 8),
  ('AULA 616 (LABO QUIMICA)', '616', 'FCyT-055', 0, '{"total": 75, "examen": 60}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 8),
  ('AULA 616A (MEZANINE) LABO QMC', '616A', 'FCyT-056', 1, '{"total": 30, "examen": 20}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 8),
  ('LABORATORIO DE SERVICIOS', 'LABSER', 'FCyT-057', 1, '{"total": 7, "examen": 7}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 8),
  ('AULA QUIMICA', 'QMCDEP', 'FCyT-058', 1, '{"total": 7, "examen": 7}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 8),
  ('AGROQUIMICO', 'AGROQUI', 'FCyT-059', 1, '{"total": 20, "examen": 10}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 9),
  ('BIODIVERSIDAD', 'BIODIV', 'FCyT-060', 1, '{"total": 20, "examen": 10}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 9),
  ('LABORATORIO BIOTECNOLOGIA', 'BIOTEC', 'FCyT-061', 0, '{"total": 20, "examen": 10}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 9),
  ('LABORATORIO CHAGAS', 'CHAGAS', 'FCyT-062', 0, '{"total": 20, "examen": 10}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 9),
  ('AUDITORIO AGROQUIMICO', 'AUDIT', 'FCyT-063', 0, '{"total": 25, "examen": 13}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 5, 10),
  ('LABORATORIO AGROQUIMICO', 'LAB', 'FCyT-064', 0, '{"total": 25, "examen": 13}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 10),
  ('AUDITORIO MEMI 1', 'AUDIT', 'FCyT-065', 2, '{"total": 30, "examen": 15}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 5, 11),
  ('AUDITORIO MEMI 2', 'AUDMEMI', 'FCyT-066', 2, '{"total": 30, "examen": 15}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 5, 11),
  ('LABORATORIO MATEMATICAS', 'LABMAT', 'FCyT-067', 0, '{"total": 30, "examen": 15}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 11),
  ('DIRECCION MATEMATICAS', 'MATDIR', 'FCyT-068', 1, '{"total": 7, "examen": 7}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 11),
  ('DIRECCION DEL MEMI', 'MEMIDIR', 'FCyT-069', 1, '{"total": 5, "examen": 5}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 11),
  ('OFICINA TESISTAS INF-SIST', 'OFMEMI', 'FCyT-070', 1, '{"total": 7, "examen": 7}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 11),
  ('DEPARTAMENTO POSTGRADO', 'POSDEP', 'FCyT-071', 1, '{"total": 7, "examen": 7}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 11),
  ('AULAS PROGR. AGUAS', 'AGUAS', 'FCyT-072', 1, '{"total": 25, "examen": 13}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 12),
  ('AULAS PROGR. ALIMENTOS Y AGUAS', 'ALIM', 'FCyT-073', 0, '{"total": 25, "examen": 13}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 12),
  ('AULAS PROGR. ALIMENTOS Y AGUAS', 'MICBIO', 'FCyT-074', 1, '{"total": 20, "examen": 20}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 12),
  ('AULA LABORATORIO MICROBIOLOGIA', 'MICBOL', 'FCyT-075', 1, '{"total": 20, "examen": 10}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 3, 12),
  ('AUDITORIO INDUSTRIAL', 'AUDIND', 'FCyT-076', 1, '{"total": 55, "examen": 40}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 5, 13),
  ('AULA CONSULTA TESISTAS', 'CAE', 'FCyT-077', 0, '{"total": 1, "examen": 1}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 13),
  ('DEPARTAMENTO INDUSTRIAS', 'INDDEP', 'FCyT-078', 1, '{"total": 7, "examen": 7}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 4, 13),
  ('AULA 690B', '690B', 'FCyT-079', 0, '{"total": 75, "examen": 45}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 690C', '690C', 'FCyT-080', 0, '{"total": 65, "examen": 35}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 690D', '690D', 'FCyT-081', 0, '{"total": 75, "examen": 45}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 691A', '691A', 'FCyT-082', 1, '{"total": 180, "examen": 130}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 691B', '691B', 'FCyT-083', 1, '{"total": 180, "examen": 130}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 691C', '691C', 'FCyT-084', 1, '{"total": 120, "examen": 90}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 691D', '691D', 'FCyT-085', 1, '{"total": 125, "examen": 95}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 691E', '691E', 'FCyT-086', 1, '{"total": 180, "examen": 130}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 691F', '691F', 'FCyT-087', 1, '{"total": 180, "examen": 130}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 692A', '692A', 'FCyT-088', 2, '{"total": 180, "examen": 130}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 692B', '692B', 'FCyT-089', 2, '{"total": 180, "examen": 130}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 692C', '692C', 'FCyT-090', 2, '{"total": 125, "examen": 95}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 692D', '692D', 'FCyT-091', 2, '{"total": 125, "examen": 95}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 692E', '692E', 'FCyT-092', 2, '{"total": 180, "examen": 130}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 692F', '692F', 'FCyT-093', 2, '{"total": 180, "examen": 130}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 692G', '692G', 'FCyT-094', 2, '{"total": 80, "examen": 50}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 692H', '692H', 'FCyT-095', 2, '{"total": 80, "examen": 50}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 693A', '693A', 'FCyT-096', 3, '{"total": 160, "examen": 140}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 693B', '693B', 'FCyT-097', 3, '{"total": 160, "examen": 140}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 693C', '693C', 'FCyT-098', 3, '{"total": 125, "examen": 95}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA 693D', '693D', 'FCyT-099', 3, '{"total": 125, "examen": 95}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 14),
  ('AULA COMUN PLANTA BAJA (CIVIL)', '680A', 'FCyT-100', 0, '{"total": 45, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA DPTO QUIMICA', '680J', 'FCyT-101', 0, '{"total": 25, "examen": 15}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('LABORATORIO 1 CIVIL', '680L1CI', 'FCyT-102', 0, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA COMUN 1ER PISO(MAT NOUSA)', '681A', 'FCyT-103', 1, '{"total": 45, "examen": 25}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA COMUN 1ER PISO (MECANICA)', '681L7', 'FCyT-104', 1, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA COMUN 2DO PISO(ELECTRICA)', '682A', 'FCyT-105', 2, '{"total": 45, "examen": 25}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA COMUN 2DO PISO(INDUSTRIAL', '682B', 'FCyT-106', 2, '{"total": 45, "examen": 25}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('LABORATORIO2DO PISO(INDUSTRIAL', '682L0IN', 'FCyT-107', 2, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA COMUN 2DO PISO(ELECTRICA)', '682L1', 'FCyT-108', 2, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA COMUN 2DO PISO(ELECTRICA)', '682L2', 'FCyT-109', 2, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA COMUN 2DO PISO(ELECTRICA)', '682L3', 'FCyT-110', 2, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA COMUN 2DO PISO(ELECTRICA)', '682L4', 'FCyT-111', 2, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('LABORATORIO2DO PISO(INDUSTRIAL', '682L6IN', 'FCyT-112', 2, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('LABORATORIO2DO PISO(INDUSTRIAL', '682L7IN', 'FCyT-113', 2, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('LABORATORIO2DO PISO(INDUSTRIAL', '682L8IN', 'FCyT-114', 2, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA COMUN 3ER PISO(BIOLOGIA)', '683A', 'FCyT-115', 3, '{"total": 45, "examen": 25}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA 3ER PISO(ALIMENTOS)', '683B', 'FCyT-116', 3, '{"total": 45, "examen": 25}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA 3ER PISO(QUIMICA)', '683J', 'FCyT-117', 3, '{"total": 30, "examen": 20}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA COMUN 4TO PISO', '684A', 'FCyT-118', 4, '{"total": 45, "examen": 25}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('AULA LABO 4TO PISO (FISICA)', '684B', 'FCyT-119', 4, '{"total": 45, "examen": 25}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('LABORATORIO 4TO PISO (FISICA)', '684L0', 'FCyT-120', 4, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('LABORATORIO 4TO PISO (FISICA)', '684L1FI', 'FCyT-121', 4, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('LABORATORIO 4TO PISO FISICA', '684L6', 'FCyT-122', 4, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('LABORATORIO 4TO PISO (FISICA)', '684L7', 'FCyT-123', 4, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('LABORATORIO 4TO PISO (FISICA)', '684L8', 'FCyT-124', 4, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15),
  ('LABORATORIO METROLOGIA', 'LABMETR', 'FCyT-125', 1, '{"total": 30, "examen": 30}'::jsonb, '{"largo": 5, "ancho": 10, "alto": 3, "unid_med": "metros"}'::jsonb, TRUE, 1, 15);

INSERT INTO infraestructura.activos (nia, nombre, descripcion, ambiente_id)
VALUES
  (
    'NIA-0001',
    'Proyector Epson X12',
    'Proyector principal del auditorio central',
    (SELECT id FROM infraestructura.ambientes WHERE codigo = 'AUD-001')
  ),
  (
    'NIA-0002',
    'Router Cisco 2900',
    'Router principal del laboratorio de redes',
    (SELECT id FROM infraestructura.ambientes WHERE codigo = '55555')
  ),
  (
    'NIA-0003',
    'Computadora Lenovo AIO',
    'Equipo para practicas de software',
    (SELECT id FROM infraestructura.ambientes WHERE codigo = '77777')
  ),
  (
    'NIA-0004',
    'Aire acondicionado Samsung 36k',
    'Equipo de climatizacion del consejo academico',
    (SELECT id FROM infraestructura.ambientes WHERE codigo = 'CON-001')
  ),
  (
    'NIA-0005',
    'Juego de pupitres metalicos',
    'Lote de 30 pupitres para aulas',
    (SELECT id FROM infraestructura.ambientes WHERE codigo = '69111')
  );
            `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
			DROP SCHEMA IF EXISTS infraestructura CASCADE;
    `);
  }
}
